### ISSUE TITLE
コメント：TAMURA

### ISSUE THREAD

**Issue by impactfactor** [UTokyo-SDP/aws-api-a3x#17]
RECOGNITION:外国のTVをみていた時に、出演者を差がいてみてみる。どの程度の時間で、どの程度の範囲で学習データがあるのか利用の上では関心があります。サービスの内奥の説明として学習データの追加できるのかの点は事前にわかった方がよいかと思いました。

**Comment by univoid** [comment]
コメントありがとうございます．参考になります．

**Comment by zenoWZH** [comment]
どの程度の時間で、どの程度の範囲は実際amazonのサービスで決まられるのことです。
