### ISSUE TITLE
ReviewBySatish

### ISSUE THREAD

**Issue by ictish** [UTokyo-SDP/aws-api-a3x#20]
1. Celebrity Recognition: Quite interesting and something I would want to use.

2. Will it recognize new celebrities?

3. It was easy to understand presentation.

**Comment by univoid** [comment]
Thanks for your comments.
It is a hard question for me to answer: "Will it recognize new celebrities?" 
Because the recognization function is based on [AWS Rekogniztion API](https://aws.amazon.com/jp/rekognition/).
Maybe Amazon will answer it.  : )
